language: python
python:
- '3.5'

sudo: required
dist: xenial

install:
- sudo apt-get install texlive-xetex texlive-latex-recommended texlive-latex-extra texlive-fonts-recommended texlive-context
- pip install "notebook==4.1" requests jupyter_cms jupyter_dashboards

addons:
  apt_packages:
  - pandoc
script:
  - ls /sys/devices/system/cpu/
  - bash tools/travis-deploy.sh

env:
  global:
  - ENCRYPTION_LABEL: dc3e238ed4e4
  - COMMIT_AUTHOR_EMAIL: stefanos1316@gmail.com

